### ISSUE TITLE
Typo at: https://js.zonayed.me/basic/post-16

### ISSUE THREAD

**Issue by TareqMonwer** [zonayedpca/js.zonayed.me#38]
![image](https://user-images.githubusercontent.com/33314452/90266287-8e68e380-de75-11ea-979e-aa84bf781f4a.png)

**Comment by zonayedpca** [comment]
ধন্যবাদ ভাই ধরিয়ে দেবার জন্য... ফিক্স করে দিবো

**Comment by TareqMonwer** [comment]
My pleasure vai.
