### ISSUE TITLE
জাভাস্ক্রিপ্ট অ্যাডভান্সঃ ফাংশন কন্সট্রাকটর(Constructor) এবং ‘new’ কীওয়ার্ড

### ISSUE THREAD

**Issue by rajudhaka** [zonayedpca/js.zonayed.me#9]
সমস্যা বিস্তারিতঃ এখানে এই উদাহরনে সেটা semir কে. Hope it will be samir. Thank you very much for the nice content.

**Comment by SabbirPulok** [comment]
এখন es6 এ class keyword  চলে আসছে, তাই আগের মত function use করে class বানানোর আর কোন দরকার নেই।

**Comment by Ontorok** [comment]
আহারে 'this'। কত যে ভুগাইলা আমারে। ভুগাভুগির খেলা শেষ। সোনার বাংলাদেশ।

**Comment by pronazmul** [comment]
very helpful blog.
